function filtered_data = bp_filter(data,sr,fq1,fq2,filteruse)
% methods use: 
% {'filterls','fir1', 'gaussian'}; 
switch filteruse 
    case 'filterls'
        filtered_data = eegfilt_pac(data,sr,fq1,fq2); % just filtering
    case 'fir1'
        filtered_data = eegfilt_fir1(data,sr,fq1,fq2); % just filtering
    case 'gaussian'
        filtered_data=...
            gaussian_filter_signal(...
            'output_type',...
            'analytic_signal',...
            'raw_signal',...
            data,...
            'sampling_rate',...
            sr,...
            'frequency_domain_standard_deviation',...
            (fq2-fq1)/3,...
            'center_frequency',...
            fq1,...
            'frequency_domain_standard_deviation',...
            0.2);
end

end